# Variables
@base_url = http://localhost:3333

# Health check
# @name healthCheck
GET {{base_url}}/health

###

# Get rooms
# @name getRooms
GET {{base_url}}/rooms

###

# Create room
# @name createRoom
POST {{base_url}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Sala de Teste 2",
  "description": "Sala de teste para o projeto"
}


###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{base_url}}/rooms/{{roomId}}/questions

###

# Create question
POST {{base_url}}/rooms/{{roomId}}/questions
Accept: application/json
Content-Type: application/json

{
  "question": "Qual a capital do Brasil?",
  "answer": "Brasília"
}

